# TODO use this in auto-gen to make file names and comments
module_name: rear_left_dam
# TODO delete this
gophercan_module_id: 2

data_input_methods:
    adc_channels:
        ADC1_IN5:
            sensor: "test_analog_sensor"
            min_frequency: 100

        ADC1_IN6:
            sensor: "test_resistive_sensor"
            min_frequency: 100
            
    can_sensors:
        can_sensor_1:
            sensor: "test_can_sensor"

parameters_produced:
    float_tester:
        produced_by: ADC1_IN5
        sensor_output: voltage
        filter_subparams:
        buffering:
            num_samples_buffered: 100

    float_tester_2:
        produced_by: ADC1_IN6
        sensor_output: current
        filter_subparams:
        buffering:
            num_samples_buffered: 100
            
    float_tester_3:
        produced_by: can_sensor_1
        sensor_output: d16_fixed
        filter_subparams:
        buffering:
            num_samples_buffered: 1
            
    float_tester_4:
        produced_by: can_sensor_1
        sensor_output: u16_raw
        filter_subparams:
        buffering:
            num_samples_buffered: 1
            
    float_tester_5:
        produced_by: can_sensor_1
        sensor_output: float_1_raw
        filter_subparams:
        buffering:
            num_samples_buffered: 1
            
    float_tester_6:
        produced_by: can_sensor_1
        sensor_output: float_2_scaled
        filter_subparams:
        buffering:
            num_samples_buffered: 1


buckets:
    bucket_1:
        id: 1
        frequency: 10
        parameters:
            - float_tester
            - float_tester_2

    bucket_2:
        id: 2
        frequency: 50
        parameters:
            - float_tester_3
            - float_tester_4

    bucket_3:
        id: 3
        frequency: 1
        parameters:
            - float_tester_5
            - float_tester_6

